// New Seed Data for Civil, Interiors, Hardware, Electrical, and Plumbing & Bath E-Commerce Platform

export const usersData = [
  {
    name: 'Admin Supervisor',
    email: 'admin@nexus.com',
    password: 'password123',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    phone: '+91 98765 43210',
    address: {
      street: '42 Commercial Boulevard, Scheme 54, Vijay Nagar',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452010',
      country: 'India',
    },
  },
  {
    name: 'Vikram Mehta (Contractor)',
    email: 'vikram@example.com',
    password: 'password123',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    phone: '+91 98200 12345',
    address: {
      street: 'Flat 402, Brilliant Titanium, Scheme No 78',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452010',
      country: 'India',
    },
  },
  {
    name: 'Priya Sharma (Interior Architect)',
    email: 'priya@example.com',
    password: 'password123',
    role: 'user',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    phone: '+91 98111 22334',
    address: {
      street: 'Villa 12, Silver Springs, Bypass Road',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452020',
      country: 'India',
    },
  },
  {
    name: 'Rohan Verma (Express Rider)',
    email: 'rider@nexus.com',
    password: 'password123',
    role: 'delivery',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    phone: '+91 98333 44556',
    vehicleType: 'Bike',
    vehicleNumber: 'MP 09 CZ 4421',
    serviceCity: 'Indore',
    servicePincodes: ['452010', '452001', '452002', '452014'],
    isAvailable: true,
    earnings: { today: 120, total: 2480 },
  },
  {
    name: 'Amit Patel (Swift EV Courier)',
    email: 'rider2@nexus.com',
    password: 'password123',
    role: 'delivery',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    phone: '+91 98444 77889',
    vehicleType: 'Scooter',
    vehicleNumber: 'MP 09 EK 9876',
    serviceCity: 'Indore',
    servicePincodes: ['452016', '452009', '452020', '453331'],
    isAvailable: true,
    earnings: { today: 80, total: 1840 },
  },
  // Demo Vendors / Merchants
  {
    name: 'Rajesh Agrawal',
    email: 'vendor@nexus.com',
    password: 'password123',
    role: 'vendor',
    vendorStatus: 'approved',
    storeName: 'Apex Hardware & Tools',
    storeDescription: 'Premier authorized distributor for professional power tools, high-tensile fasteners, architectural hinges, and plumbing fixtures.',
    storeLogo: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=200&auto=format&fit=crop&q=80',
    storeBanner: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=1200&auto=format&fit=crop&q=80',
    businessEmail: 'sales@apexhardware.com',
    businessPhone: '+91 98260 55443',
    taxId: '23AABCA1234F1Z8',
    commissionRate: 8,
    bankDetails: {
      accountHolderName: 'Apex Hardware Private Limited',
      accountNumber: '50200048192841',
      bankName: 'HDFC Bank - Vijay Nagar Branch',
      routingOrIfsc: 'HDFC0000281',
    },
    address: {
      street: 'Plot 18, Industrial Estate, Sector B',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452015',
      country: 'India',
    },
  },
  {
    name: 'Sunita Kapoor',
    email: 'decor@nexus.com',
    password: 'password123',
    role: 'vendor',
    vendorStatus: 'approved',
    storeName: 'Prime Interiors & Lighting',
    storeDescription: 'Luxury architectural lights, smart modular switches, acoustic panels, designer veneers, and Italian sanitary fixtures.',
    storeLogo: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=200&auto=format&fit=crop&q=80',
    storeBanner: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&auto=format&fit=crop&q=80',
    businessEmail: 'contact@primeinteriors.in',
    businessPhone: '+91 98930 11223',
    taxId: '23BBCCD5678G2Z1',
    commissionRate: 12,
    bankDetails: {
      accountHolderName: 'Prime Interiors Studio',
      accountNumber: '918020038472910',
      bankName: 'ICICI Bank - Palasia Branch',
      routingOrIfsc: 'ICIC0001092',
    },
    address: {
      street: '14/2 South Tukoganj, MG Road',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452001',
      country: 'India',
    },
  },
  {
    name: 'Manish Chouksey',
    email: 'materials@nexus.com',
    password: 'password123',
    role: 'vendor',
    vendorStatus: 'approved',
    storeName: 'BuildCraft Materials Co.',
    storeDescription: 'Wholesale supplier of weather-shield cement, BWP marine plywood, polymer waterproofing, and high-pressure CPVC piping systems.',
    storeLogo: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=200&auto=format&fit=crop&q=80',
    storeBanner: 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?w=1200&auto=format&fit=crop&q=80',
    businessEmail: 'info@buildcraft.co.in',
    businessPhone: '+91 98270 99881',
    taxId: '23CCDEF9012H3Z4',
    commissionRate: 10,
    bankDetails: {
      accountHolderName: 'BuildCraft Materials LLP',
      accountNumber: '381920047261',
      bankName: 'State Bank of India',
      routingOrIfsc: 'SBIN0003011',
    },
    address: {
      street: 'Ring Road, Near Dewas Naka',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '452010',
      country: 'India',
    },
  },
  {
    name: 'Kavita Joshi',
    email: 'pending@nexus.com',
    password: 'password123',
    role: 'vendor',
    vendorStatus: 'pending',
    storeName: 'Royal Stone & Granite Hub',
    storeDescription: 'Exotic granite slabs, natural sandstone, and high-precision CNC stone engraving services.',
    storeLogo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&auto=format&fit=crop&q=80',
    storeBanner: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&auto=format&fit=crop&q=80',
    businessEmail: 'kavita@royalstone.com',
    businessPhone: '+91 98190 77665',
    taxId: '23DDGHJ4412K5M2',
    commissionRate: 10,
    bankDetails: {
      accountHolderName: 'Royal Stone Hub',
      accountNumber: '110029384756',
      bankName: 'Axis Bank',
      routingOrIfsc: 'UTIB0000451',
    },
    address: {
      street: 'Bypass Road, Manglia',
      city: 'Indore',
      state: 'Madhya Pradesh',
      postalCode: '453771',
      country: 'India',
    },
  },
];

export const categoriesData = [
  // 1. Civil & Interiors
  {
    name: 'Civil & Interiors',
    slug: 'civil-interiors',
    description: 'High-strength cement, designer vitrified tiling, marine plywood, premium adhesives, waterproofing membranes, and luxury wall emulsions.',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=600&auto=format&fit=crop&q=80',
    icon: 'home',
    itemCount: 42,
    subcategories: [
      { name: 'Cement', slug: 'cement', description: 'OPC, PPC, and rapid-hardening construction cement bags', image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=400&auto=format&fit=crop&q=80' },
      { name: 'Tiling', slug: 'tiling', description: 'Vitrified floor tiles, ceramic wall tiles, grouts & epoxy', image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&auto=format&fit=crop&q=80' },
      { name: 'Plywood, MDF & HDHMR', slug: 'plywood-mdf-hdhmr', description: 'Calibrated marine ply, high-density moisture-resistant boards', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&auto=format&fit=crop&q=80' },
      { name: 'Fevicol', slug: 'fevicol', description: 'Woodworking adhesives, heat-resistant & marine synthetic resins', image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=80' },
      { name: 'Waterproofing', slug: 'waterproofing', description: 'Liquid membranes, damp-proof coatings & integral bonding agents', image: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=400&auto=format&fit=crop&q=80' },
      { name: 'Painting', slug: 'painting', description: 'Luxury interior/exterior emulsions, wall putty & primers', image: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&auto=format&fit=crop&q=80' },
    ],
  },
  // 2. Furniture & Architectural Hardware
  {
    name: 'Furniture & Architectural Hardware',
    slug: 'furniture-architectural-hardware',
    description: 'Soft-close hinges, heavy-duty drawer telescopic slides, modular kitchen organizers, hydraulic bed fittings, and high-security smart door locks.',
    image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80',
    icon: 'gamepad',
    itemCount: 38,
    subcategories: [
      { name: 'Hinges, Channels & Handles', slug: 'hinges-channels-handles', description: '3D soft-close concealed hinges, ball-bearing channels & designer brass handles', image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=400&auto=format&fit=crop&q=80' },
      { name: 'Kitchen Systems & Accessories', slug: 'kitchen-systems-accessories', description: 'Modular SS wire baskets, magic corners, pantry pullouts & cutlery units', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=400&auto=format&fit=crop&q=80' },
      { name: 'Wardrobe & Bed Fittings', slug: 'wardrobe-bed-fittings', description: 'Heavy gas-lift bed mechanisms, sliding wardrobe roller channels & tie racks', image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&auto=format&fit=crop&q=80' },
      { name: 'Door Locks & Hardware', slug: 'door-locks-hardware', description: 'Biometric smart mortise locks, stainless steel aldrops, handles & floor springs', image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=400&auto=format&fit=crop&q=80' },
    ],
  },
  // 3. Electrical
  {
    name: 'Electrical',
    slug: 'electrical',
    description: 'FR copper wiring, modular distribution boards, designer glass switch plates, fire-retardant conduits, and architectural ambient LED lighting.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=600&auto=format&fit=crop&q=80',
    icon: 'smartphone',
    itemCount: 45,
    subcategories: [
      { name: 'Wires, MCB & Distribution Boards', slug: 'wires-mcb-distribution-boards', description: '90m flame-retardant copper wires, isolators, RCCB, and SPN DB boxes', image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80' },
      { name: 'Switches & Sockets', slug: 'switches-sockets', description: 'Modular rocker switches, 16A power sockets, USB plates & fan regulators', image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400&auto=format&fit=crop&q=80' },
      { name: 'Electrical Conduits', slug: 'electrical-conduits', description: 'Heavy-duty PVC rigid conduits, bends, junction boxes & flexible pipes', image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=400&auto=format&fit=crop&q=80' },
      { name: 'Lighting', slug: 'lighting', description: 'Recessed COB LED downlights, magnetic track lights & ambient profile strips', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&auto=format&fit=crop&q=80' },
    ],
  },
  // 4. Plumbing, Sanitary & Bath
  {
    name: 'Plumbing, Sanitary & Bath',
    slug: 'plumbing-sanitary-bath',
    description: 'Chlorinated CPVC plumbing pipes, multi-layer UV overhead water storage tanks, brass single-lever faucets, and ceramic wall-hung sanitary ware.',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
    icon: 'headphones',
    itemCount: 36,
    subcategories: [
      { name: 'CPVC Pipes & Overhead Tanks', slug: 'cpvc-pipes-overhead-tanks', description: 'High-pressure SDR 11 CPVC pipes, brass transition fittings & solvent cement', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&auto=format&fit=crop&q=80' },
      { name: 'Sanitary & Bath Fittings', slug: 'sanitary-bath-fittings', description: 'Single lever basin mixers, wall-hung WC commodes & overhead rain showers', image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=400&auto=format&fit=crop&q=80' },
      { name: 'Overhead Tanks', slug: 'overhead-tanks', description: 'Anti-bacterial 3-layer and 4-layer 500L to 2000L virgin plastic storage tanks', image: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=400&auto=format&fit=crop&q=80' },
    ],
  },
];

export const getProductsData = (categoryMap) => [
  // ==========================================
  // CATEGORY 1: CIVIL & INTERIORS
  // ==========================================
  {
    name: 'UltraTech Super Weather-Shield Cement 50kg',
    slug: 'ultratech-super-weather-shield-cement-50kg',
    description: 'Engineered with Micro-Fine particle technology for superior water repellency, rapid setting, and ultimate structural compression strength.',
    price: 435,
    originalPrice: 480,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'cement',
    brand: 'UltraTech',
    countInStock: 250,
    images: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 124,
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['cement', 'civil', 'construction', 'ultratech'],
    specifications: [
      { name: 'Grade', value: 'PPC High Performance' },
      { name: 'Weight', value: '50 Kg Bag' },
      { name: 'Standard', value: 'IS 1489 (Part 1)' },
    ],
    soldCount: 840,
  },
  {
    name: 'Kajaria Grandeur Royal Italian Vitrified Tiles 600x1200mm',
    slug: 'kajaria-grandeur-royal-italian-vitrified-tiles',
    description: 'High-gloss polished glazed vitrified tile (PGVT) with Italian Statuario marble veining, stain resistance, and nano-seal anti-scratch coating.',
    price: 1850,
    originalPrice: 2200,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'tiling',
    brand: 'Kajaria',
    countInStock: 80,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    numReviews: 68,
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isFlashDeal: false,
    tags: ['tiles', 'flooring', 'vitrified', 'marble'],
    specifications: [
      { name: 'Size', value: '600 x 1200 mm' },
      { name: 'Coverage', value: '15.5 Sq.ft per Box (2 Pcs)' },
      { name: 'Finish', value: 'High Gloss Mirror Polish' },
    ],
    soldCount: 310,
  },
  {
    name: 'CenturyPly Club Prime BWP Marine Grade Plywood (19mm)',
    slug: 'centuryply-club-prime-bwp-marine-plywood-19mm',
    description: '100% boiling waterproof (BWP) marine plywood with patented ViroKill antimicrobial technology and glue line protection against borer and termites.',
    price: 3450,
    originalPrice: 3890,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'plywood-mdf-hdhmr',
    brand: 'CenturyPly',
    countInStock: 45,
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1540518614846-7ede433c4ef7?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 89,
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: false,
    tags: ['plywood', 'marine', 'interiors', 'carpentry'],
    specifications: [
      { name: 'Thickness', value: '19 mm' },
      { name: 'Sheet Dimensions', value: '8ft x 4ft (32 Sq.ft)' },
      { name: 'Guarantee', value: '30-Year Warranty' },
    ],
    soldCount: 420,
  },
  {
    name: 'Fevicol Marine Waterproof Wood Adhesive (5kg Bucket)',
    slug: 'fevicol-marine-waterproof-wood-adhesive-5kg',
    description: 'Advanced waterproof synthetic resin adhesive that withstands 48 hours of continuous boiling water immersion. Ideal for kitchens, baths, and marine joinery.',
    price: 1280,
    originalPrice: 1450,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'fevicol',
    brand: 'Pidilite Fevicol',
    countInStock: 110,
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 156,
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['fevicol', 'adhesive', 'waterproof', 'pidilite'],
    specifications: [
      { name: 'Weight', value: '5 Kg Plastic Pail' },
      { name: 'Bonding Time', value: '4 to 6 Hours Full Cure' },
      { name: 'Application', value: 'Wood, Laminate, MDF, Acrylic' },
    ],
    soldCount: 950,
  },
  {
    name: 'Dr. Fixit Pidifin 2K Polymer Waterproofing Coating (15kg)',
    slug: 'dr-fixit-pidifin-2k-polymer-waterproofing-15kg',
    description: 'Two-component acrylic polymer modified elastomeric waterproofing coating for terrace slabs, sunken bathrooms, water tanks, and external foundations.',
    price: 2650,
    originalPrice: 2999,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'waterproofing',
    brand: 'Dr. Fixit',
    countInStock: 60,
    images: [
      'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    numReviews: 73,
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: false,
    tags: ['waterproofing', 'pidilite', 'drfixit', 'roofing'],
    specifications: [
      { name: 'Pack Size', value: '15 Kg (Liquid + Powder)' },
      { name: 'Coverage', value: '120 - 150 Sq.ft in 2 Coats' },
      { name: 'Flexibility', value: 'High Elongation Crack Bridging' },
    ],
    soldCount: 380,
  },
  {
    name: 'Asian Paints Royale Luxury Emulsion Shyne (20 Litres)',
    slug: 'asian-paints-royale-luxury-emulsion-shyne-20l',
    description: 'Ultra-luxurious Teflon surface protected interior wall emulsion with high sheen, anti-fungal shield, low VOC, and superior scrub resistance.',
    price: 8900,
    originalPrice: 9950,
    category: categoryMap['civil-interiors'],
    categoryName: 'Civil & Interiors',
    subcategory: 'painting',
    brand: 'Asian Paints',
    countInStock: 35,
    images: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 112,
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isFlashDeal: false,
    tags: ['paint', 'asianpaints', 'emulsion', 'royale'],
    specifications: [
      { name: 'Volume', value: '20 Litre Drum' },
      { name: 'Sheen Level', value: 'High Gloss Shyne' },
      { name: 'Coverage', value: '280 - 320 Sq.ft/L in 2 Coats' },
    ],
    soldCount: 290,
  },

  // ==========================================
  // CATEGORY 2: FURNITURE & ARCHITECTURAL HARDWARE
  // ==========================================
  {
    name: 'Häfele Metalla 3D Soft-Close Concealed Hinges (Pack of 8)',
    slug: 'hafele-metalla-3d-soft-close-concealed-hinges',
    description: 'Precision German-engineered 110-degree clip-on hinges with integrated hydraulic dampers for silent, smooth cabinet door closure and 3-way adjustment.',
    price: 1450,
    originalPrice: 1750,
    category: categoryMap['furniture-architectural-hardware'],
    categoryName: 'Furniture & Architectural Hardware',
    subcategory: 'hinges-channels-handles',
    brand: 'Häfele',
    countInStock: 95,
    images: [
      'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 98,
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['hardware', 'hinges', 'hafele', 'cabinets'],
    specifications: [
      { name: 'Opening Angle', value: '110 Degrees' },
      { name: 'Material', value: 'Nickel-Plated Cold Rolled Steel' },
      { name: 'Cycles', value: '50,000 Tested Opening Cycles' },
    ],
    soldCount: 620,
  },
  {
    name: 'Sleek SS-304 Modular Kitchen Magic Corner Unit Organiser',
    slug: 'sleek-ss304-modular-kitchen-magic-corner-unit',
    description: 'Blind corner pull-out basket system made of mirror-polished SS 304 with heavy-duty soft-closing slides and anti-slip acrylic mats.',
    price: 14800,
    originalPrice: 17900,
    category: categoryMap['furniture-architectural-hardware'],
    categoryName: 'Furniture & Architectural Hardware',
    subcategory: 'kitchen-systems-accessories',
    brand: 'Sleek by Asian Paints',
    countInStock: 20,
    images: [
      'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    numReviews: 45,
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isFlashDeal: false,
    tags: ['kitchen', 'modular', 'ss304', 'storage'],
    specifications: [
      { name: 'Basket Material', value: 'Food-Grade Stainless Steel 304' },
      { name: 'Load Capacity', value: '35 Kg Total Weight' },
      { name: 'Cabinet Width', value: '900mm to 1050mm Corner' },
    ],
    soldCount: 140,
  },
  {
    name: 'Hettich Heavy Gas-Spring Hydraulic Bed Lift Mechanism (150kg)',
    slug: 'hettich-heavy-gas-spring-hydraulic-bed-lift-150kg',
    description: 'Effortless under-bed storage lifting frame featuring twin nitrogen-filled gas struts for king-size and queen-size wooden bed boxes.',
    price: 4890,
    originalPrice: 5600,
    category: categoryMap['furniture-architectural-hardware'],
    categoryName: 'Furniture & Architectural Hardware',
    subcategory: 'wardrobe-bed-fittings',
    brand: 'Hettich',
    countInStock: 50,
    images: [
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    numReviews: 54,
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: false,
    tags: ['bedfittings', 'hettich', 'hydraulic', 'furniture'],
    specifications: [
      { name: 'Lifting Force', value: '1500 N (150 Kg Capacity)' },
      { name: 'Frame Length', value: '5 Feet (1500mm)' },
      { name: 'Mechanism', value: 'Cold Rolled Electroplated Steel' },
    ],
    soldCount: 310,
  },
  {
    name: 'Yale YDME 100 Nx Biometric Smart Touchscreen Mortise Lock',
    slug: 'yale-ydme-100-nx-biometric-smart-door-lock',
    description: '360° rapid fingerprint scanner, PIN passcode, RFID smart cards, mechanical override key, and anti-tamper security alarm system.',
    price: 16999,
    originalPrice: 21990,
    category: categoryMap['furniture-architectural-hardware'],
    categoryName: 'Furniture & Architectural Hardware',
    subcategory: 'door-locks-hardware',
    brand: 'Yale',
    countInStock: 28,
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 76,
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isFlashDeal: true,
    tags: ['smartlock', 'yale', 'biometric', 'security'],
    specifications: [
      { name: 'Access Modes', value: 'Fingerprint, PIN, RFID Card, Key' },
      { name: 'Fingerprint Capacity', value: 'Up to 100 Biometric Profiles' },
      { name: 'Door Thickness', value: '35mm - 65mm Wooden Doors' },
    ],
    soldCount: 220,
  },

  // ==========================================
  // CATEGORY 3: ELECTRICAL
  // ==========================================
  {
    name: 'Havells LifeLine Plus 2.5 sq mm Flame Retardant Wire (90m)',
    slug: 'havells-lifeline-plus-25sqmm-fr-wire-90m',
    description: '100% pure electrolytic high-conductivity copper conductor insulated with HRFR (Heat Resistant Flame Retardant) low smoke PVC.',
    price: 2450,
    originalPrice: 2850,
    category: categoryMap['electrical'],
    categoryName: 'Electrical',
    subcategory: 'wires-mcb-distribution-boards',
    brand: 'Havells',
    countInStock: 140,
    images: [
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 180,
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['wires', 'havells', 'electrical', 'copper'],
    specifications: [
      { name: 'Cross Section', value: '2.5 Sq. mm' },
      { name: 'Length', value: '90 Metres Coil' },
      { name: 'Standard', value: 'IS 694 Certified' },
    ],
    soldCount: 1150,
  },
  {
    name: 'Schneider AvatarOn Luxury Glass Modular Switch Set (12-Module)',
    slug: 'schneider-avataron-luxury-glass-modular-switch-set',
    description: 'Frameless ultra-slim frameless crystal glass faceplate with soft-click illuminated rocker switches and child-safety shuttered power sockets.',
    price: 3890,
    originalPrice: 4600,
    category: categoryMap['electrical'],
    categoryName: 'Electrical',
    subcategory: 'switches-sockets',
    brand: 'Schneider Electric',
    countInStock: 65,
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    numReviews: 84,
    isFeatured: true,
    isTrending: false,
    isNewArrival: true,
    isFlashDeal: false,
    tags: ['switches', 'schneider', 'modular', 'interiors'],
    specifications: [
      { name: 'Capacity', value: '12 Module Grid Plate' },
      { name: 'Plate Material', value: 'Toughened Tempered Glass' },
      { name: 'Rated Current', value: '10A / 16A 240V AC' },
    ],
    soldCount: 390,
  },
  {
    name: 'Precision Heavy-Gauge PVC Rigid Electrical Conduits (25mm, 10 Pcs)',
    slug: 'precision-heavy-gauge-pvc-rigid-conduits-25mm',
    description: 'High impact and fire-retardant virgin PVC conduit pipes for concealed slab and wall wiring installations with smooth interior bore for easy wire pulling.',
    price: 1150,
    originalPrice: 1350,
    category: categoryMap['electrical'],
    categoryName: 'Electrical',
    subcategory: 'electrical-conduits',
    brand: 'Precision Pipes',
    countInStock: 120,
    images: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.7,
    numReviews: 62,
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: false,
    tags: ['conduits', 'pvc', 'electrical', 'wiring'],
    specifications: [
      { name: 'Diameter', value: '25 mm Outer Diameter' },
      { name: 'Length', value: '3 Metres per Pipe (Pack of 10)' },
      { name: 'Class', value: 'Heavy Duty Rigid' },
    ],
    soldCount: 510,
  },
  {
    name: 'Philips Hue Architectural Magnetic Recessed COB LED Light 15W',
    slug: 'philips-architectural-magnetic-recessed-cob-led-15w',
    description: 'High CRI 95+ anti-glare deep recessed spotlight with optical reflector for dramatic accent illumination and warm dimming control.',
    price: 1490,
    originalPrice: 1899,
    category: categoryMap['electrical'],
    categoryName: 'Electrical',
    subcategory: 'lighting',
    brand: 'Philips',
    countInStock: 85,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 138,
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isFlashDeal: true,
    tags: ['lighting', 'cob', 'philips', 'led', 'downlight'],
    specifications: [
      { name: 'Power', value: '15 Watts (1400 Lumens)' },
      { name: 'Color Temp', value: '3000K Warm White' },
      { name: 'Beam Angle', value: '36 Degree Optical Lens' },
    ],
    soldCount: 780,
  },

  // ==========================================
  // CATEGORY 4: PLUMBING, SANITARY & BATH
  // ==========================================
  {
    name: 'Astral CPVC Pro High-Pressure Hot & Cold Water Pipe (1 Inch, 10 Pcs)',
    slug: 'astral-cpvc-pro-high-pressure-hot-cold-pipe-1inch',
    description: 'Lead-free SDR-11 NSF-certified CPVC pipes suitable for 93°C hot water and cold water plumbing distribution with zero scale buildup.',
    price: 2890,
    originalPrice: 3300,
    category: categoryMap['plumbing-sanitary-bath'],
    categoryName: 'Plumbing, Sanitary & Bath',
    subcategory: 'cpvc-pipes-overhead-tanks',
    brand: 'Astral Pipes',
    countInStock: 90,
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 145,
    isFeatured: true,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['plumbing', 'cpvc', 'astral', 'pipes'],
    specifications: [
      { name: 'Size', value: '1 Inch (25mm) SDR 11' },
      { name: 'Length', value: '3 Metres per Length (10 Pcs)' },
      { name: 'Working Temp', value: 'Up to 93°C (200°F)' },
    ],
    soldCount: 920,
  },
  {
    name: 'Jaquar Alive Single Lever Basin Mixer Tap (Matte Black)',
    slug: 'jaquar-alive-single-lever-basin-mixer-matte-black',
    description: 'Forged solid virgin brass body with aerator water-saving flow and electroplated velvet matte black finish with 10-year Jaquar on-site warranty.',
    price: 4950,
    originalPrice: 5900,
    category: categoryMap['plumbing-sanitary-bath'],
    categoryName: 'Plumbing, Sanitary & Bath',
    subcategory: 'sanitary-bath-fittings',
    brand: 'Jaquar',
    countInStock: 40,
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 88,
    isFeatured: true,
    isTrending: true,
    isNewArrival: true,
    isFlashDeal: false,
    tags: ['faucet', 'jaquar', 'bathroom', 'sanitary'],
    specifications: [
      { name: 'Finish', value: 'Electroplated Matte Black' },
      { name: 'Cartridge', value: '35mm Ceramic Disc Cartridge' },
      { name: 'Warranty', value: '10 Years Complete Warranty' },
    ],
    soldCount: 340,
  },
  {
    name: 'Kohler Reach Rimless Wall-Hung WC Toilet Commode',
    slug: 'kohler-reach-rimless-wall-hung-wc-toilet-commode',
    description: 'Rimless bowl technology for 360° hygiene flush, concealed fixing, and heavy-duty UF soft-close seat cover.',
    price: 13500,
    originalPrice: 16500,
    category: categoryMap['plumbing-sanitary-bath'],
    categoryName: 'Plumbing, Sanitary & Bath',
    subcategory: 'sanitary-bath-fittings',
    brand: 'Kohler',
    countInStock: 25,
    images: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.8,
    numReviews: 52,
    isFeatured: true,
    isTrending: false,
    isNewArrival: false,
    isFlashDeal: false,
    tags: ['toilet', 'kohler', 'sanitary', 'wallhung'],
    specifications: [
      { name: 'Mount Type', value: 'Wall-Hung Concealed Tank' },
      { name: 'Flushing', value: 'Rimless Dual Flush 3/6 Litres' },
      { name: 'Seat Material', value: 'Urea-Formaldehyde Soft Close' },
    ],
    soldCount: 160,
  },
  {
    name: 'Sintex Pure 1000 Litres 4-Layer Anti-Bacterial Overhead Tank',
    slug: 'sintex-pure-1000l-4layer-anti-bacterial-overhead-tank',
    description: '100% virgin food-grade polymer tank with Microban anti-bacterial inner lining, carbon black UV barrier layer, and heat-reflective outer shell.',
    price: 7800,
    originalPrice: 9200,
    category: categoryMap['plumbing-sanitary-bath'],
    categoryName: 'Plumbing, Sanitary & Bath',
    subcategory: 'overhead-tanks',
    brand: 'Sintex',
    countInStock: 30,
    images: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
    ],
    rating: 4.9,
    numReviews: 110,
    isFeatured: false,
    isTrending: true,
    isNewArrival: false,
    isFlashDeal: true,
    tags: ['watertank', 'sintex', 'plumbing', 'storage'],
    specifications: [
      { name: 'Capacity', value: '1000 Litres' },
      { name: 'Layers', value: '4-Layer UV Protected' },
      { name: 'Material', value: '100% Virgin Food Grade Polymer' },
    ],
    soldCount: 450,
  },
];

export const getAdvertisementsData = (categoryMap) => [
  // 1. Civil & Interiors: Image Ad (Light Sage Green)
  {
    title: 'High-Grade Cement, Plywood & Waterproofing — Flat 20% OFF',
    subtitle: 'Direct bulk contractor rates on UltraTech, CenturyPly, Fevicol, and Dr. Fixit construction supplies.',
    tag: '⚡ CONTRACTOR WHOLESALE PASS',
    type: 'image',
    placement: 'category_feed',
    layout: 'split-media',
    mediaUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=800',
    badgeText: 'Grade A Certified',
    perk: 'Direct Site Truck Delivery',
    category: categoryMap['civil-interiors'],
    categorySlug: 'civil-interiors',
    buttonText: 'Explore Civil Supplies',
    link: '/shop?category=civil-interiors',
    bgGradient: 'bg-gradient-to-r from-[#ecfdf5] via-[#d1fae5] to-[#a7f3d0]',
    borderColor: 'border-emerald-200',
    isActive: true,
    order: 1,
  },
  // 2. Furniture & Architectural Hardware: Simple Ad (Light Warm Caramel Brown)
  {
    title: 'Häfele & Yale Smart Hardware Bundles + Instant ₹2,500 Voucher',
    subtitle: 'Soft-close 3D hinges, heavy telescopic channels, and biometric smart door locks for luxury homes.',
    tag: '🚪 ARCHITECTURAL HARDWARE DROP',
    type: 'simple',
    placement: 'category_feed',
    layout: 'simple-card',
    couponCode: 'HARDWARE25',
    perks: ['German Precision Tested', 'Free Screws & Templates', '10-Yr Mechanism Guarantee'],
    highlightBadge: { label: 'Architect Rebate', value: 'Extra 25% OFF' },
    category: categoryMap['furniture-architectural-hardware'],
    categorySlug: 'furniture-architectural-hardware',
    buttonText: 'Shop Hardware Deals',
    link: '/shop?category=furniture-architectural-hardware',
    bgGradient: 'bg-gradient-to-r from-[#fffbeb] via-[#fef3c7] to-[#fde68a]',
    borderColor: 'border-amber-200',
    isActive: true,
    order: 2,
  },
  // 3. Electrical: Video Ad (Light Mint Olive Green)
  {
    title: 'Havells FR Copper Wires & Schneider Glass Switch Plates in Action',
    subtitle: 'Fire-resistant wiring systems, 15W recessed COB downlights, and smart distribution panels.',
    tag: '⚡ ELECTRICAL INNOVATION 2026',
    type: 'video',
    placement: 'category_feed',
    layout: 'split-media',
    mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-of-an-electrician-connecting-wires-41617-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800',
    badgeText: 'FR Grade Wire',
    perk: 'IS 694 Fire Certified',
    category: categoryMap['electrical'],
    categorySlug: 'electrical',
    buttonText: 'Shop Electrical Range',
    link: '/shop?category=electrical',
    bgGradient: 'bg-gradient-to-r from-[#f0fdf4] via-[#dcfce7] to-[#bbf7d0]',
    borderColor: 'border-green-200',
    isActive: true,
    order: 3,
  },
  // 4. Plumbing, Sanitary & Bath: Video Ad (Light Warm Sand / Latte)
  {
    title: 'Astral CPVC Pressure Pipes & Jaquar Luxury Faucets Demo',
    subtitle: '93°C hot-cold high-pressure plumbing, rimless wall-hung WC commodes, and Sintex 4-layer tanks.',
    tag: '🚿 PLUMBING & BATH EXCELLENCE',
    type: 'video',
    placement: 'category_feed',
    layout: 'split-media',
    mediaUrl: 'https://assets.mixkit.co/videos/preview/mixkit-modern-bathroom-with-a-bathtub-and-faucet-41486-large.mp4',
    posterUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800',
    badgeText: '10-Yr Warranty',
    perk: 'Lead-Free NSF Certified',
    category: categoryMap['plumbing-sanitary-bath'],
    categorySlug: 'plumbing-sanitary-bath',
    buttonText: 'Shop Sanitary & Bath',
    link: '/shop?category=plumbing-sanitary-bath',
    bgGradient: 'bg-gradient-to-r from-[#fff7ed] via-[#ffedd5] to-[#fed7aa]',
    borderColor: 'border-orange-200',
    isActive: true,
    order: 4,
  },

  // ==========================================
  // HERO SLIDER BANNERS (Dynamic Backend Hero)
  // ==========================================
  // Hero Slide 1: Civil & Interiors
  {
    title: 'Next-Gen Building & Interior Architectural Materials',
    subtitle: 'Direct contractor supply for UltraTech Weather-Shield Cement, CenturyPly Marine Grade Plywood, and Italian Vitrified Tiles.',
    tag: '⚡ INDUSTRIAL GRADE MATERIALS',
    badgeText: 'ISO 9001 Certified Mega Warehouse',
    type: 'image',
    placement: 'hero_slide',
    layout: 'split-media',
    mediaUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18f15f6?w=1000&auto=format&fit=crop&q=80',
    highlightBadge: { label: 'Contractor Rate', value: '₹435 / Bag' },
    buttonText: 'Explore Building Drops',
    link: '/shop?category=civil-interiors',
    bgGradient: 'from-[#0f766e] via-[#0d9488] to-[#115e59]',
    borderColor: 'border-teal-300/40',
    isActive: true,
    order: 1,
  },
  // Hero Slide 2: Electrical Systems
  {
    title: 'Havells FR Pure Copper Wires & Schneider Glass Switch Plates',
    subtitle: 'Zero fire-risk wiring, 15W recessed COB architectural downlights, and smart distribution panel automation.',
    tag: '⚡ ADVANCED ELECTRICAL SYSTEMS',
    badgeText: 'IS 694 Fire Retardant Certified',
    type: 'image',
    placement: 'hero_slide',
    layout: 'split-media',
    mediaUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=1000&auto=format&fit=crop&q=80',
    highlightBadge: { label: 'Project Wholesale', value: 'Flat 25% OFF' },
    buttonText: 'Shop Electrical Systems',
    link: '/shop?category=electrical',
    bgGradient: 'from-[#0d9488] via-[#14b8a6] to-[#0f766e]',
    borderColor: 'border-teal-300/40',
    isActive: true,
    order: 2,
  },
  // Hero Slide 3: Plumbing, Bath & Smart Hardware
  {
    title: 'Astral CPVC Pro Pipes, Jaquar Faucets & Yale Biometric Locks',
    subtitle: 'High-pressure 93°C hot-cold plumbing, rimless wall-hung WC commodes, and 360° fingerprint smart mortise security.',
    tag: '🚿 SANITARY & SMART SECURITY',
    badgeText: '10-Year Comprehensive Warranty',
    type: 'image',
    placement: 'hero_slide',
    layout: 'split-media',
    mediaUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1000&auto=format&fit=crop&q=80',
    highlightBadge: { label: 'Exclusive Drop', value: 'Save Up To 35%' },
    buttonText: 'Discover Plumbing & Bath',
    link: '/shop?category=plumbing-sanitary-bath',
    bgGradient: 'from-[#115e59] via-[#0d9488] to-[#042f2e]',
    borderColor: 'border-teal-300/40',
    isActive: true,
    order: 3,
  },
];
